name: "Setup PGP Keys"
description: "My Action"
inputs:
  verbose:
    required: false
    type: string
  image:
    required: true
    type: string
  imagePullPolicy:
    required: true
    type: string
  pgpKeysSecretName:
    required: true
    type: string
runs:
  using: "composite"
  steps:
    - name: setup-pgp-keys
      run: psr --help
      shell: bash
