---
# This Github workflow will run jobs to build REPLACE_applicationname.
name: REPLACE_applicationname

on:
  push:
  pull_request_target:
    types:
      - opened
      - edited
      - synchronize
  workflow_dispatch:
permissions:
  pull-requests: write

jobs:
  minimal:
    uses: ploigos/ploigos-github-workflows/.github/workflows/minimal.yaml@main
    secrets: inherit
