# This Github workflow will run the CI Push Container Image to Repository step of the Ploigos workflow.
name: CI Push Container Image to Repository

on:
  workflow_call:
    inputs:
      verbose:
        required: false
        type: string
      image:
        required: true
        type: string
      imagePullPolicy:
        required: true
        type: string
      stepRunnerPackageName:
        required: true
        type: string
      venvPath:
        required: true
        type: string
      stepName:
        required: true
        type: string
      stepRunnerConfigDir:
        required: true
        type: string

jobs:
  ci-push-container-image-to-repository:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: ci-push-container-image-to-repository
        run: |
          echo 'CI Push Container Image to Repository'
