# This Github workflow will run the Report step of the Ploigos workflow.
name: Minimal Workflow

on:
  workflow_call:
    inputs:
      verbose:
        required: false
        default: true
        type: string
      stepRunnerConfigDir:
        required: false
        default: .
        type: string
jobs:
  continuous-integration:
    runs-on: ubuntu-latest
    steps:

      - name: setup-app-clone
        uses: actions/checkout@v3

      - name: setup-python
        uses: actions/setup-python@v3
        with:
          python-version: '3.9.12'
          architecture: 'x64'

      - name: setup-workflow-step-runner
        run: python -m pip install --upgrade git+https://github.com/ploigos/ploigos-step-runner.git@${{ inputs.psrBranch }}

      - name: ci-generate-metadata
        run: psr --help
        # run: psr -s generate-metadata -c ${{ inputs.stepRunnerConfigDir }}

      - name: ci-package-application
        run: psr --help

      - name: ci-create-container-image
        run: psr --help

      - name: ci-push-container-image-to-repository
        run: psr --help
