# This Github workflow will run the Report step of the Ploigos workflow.
name: Minimal Workflow

on:
  workflow_call:
    inputs:
      verbose:
        required: false
        type: string
      image:
        required: true
        type: string
      imagePullPolicy:
        required: true
        type: string
      stepRunnerPackageName:
        required: true
        type: string
      venvPath:
        required: true
        type: string
      stepName:
        required: true
        type: string
      stepRunnerConfigDir:
        required: true
        type: string

jobs:
  setup:
    runs-on: ubuntu-latest
    container:
      image: quay.io/ploigos/ploigos-base:latest.ubi8
    steps:
      - name: setup-app-clone
        uses: ploigos/ploigos-github-action@psr-action
        with:
          entrypoint: psr --help
#          stepName: "app-clone"
#      - name: setup-workflow-step-runner
#        uses: ploigos/ploigos-github-action@psr-action
#        with:
#          stepName: "setup-workflow-step-runner"
  continous-integration:
    needs: setup
    runs-on: ubuntu-latest
    steps:
#      - uses: actions/checkout@v3
      - name: ci-generate-metadata
        uses: ploigos/ploigos-github-action@psr-action
        with:
          stepName: "generate-metadata"
      - name: ci-create-container-image
        uses: ploigos/ploigos-github-action@psr-action
        with:
          stepName: "create-container-image"
      - name: ci-package-application
        uses: ploigos/ploigos-github-action@psr-action
        with:
          stepName: "package-application"
      - name: ci-push-container-image-to-repository
        uses: ploigos/ploigos-github-action@psr-action
        with:
          stepName: "push-container-image-to-repository"
