# This Github workflow will run the Report step of the Ploigos workflow.
name: Minimal Workflow

on:
  workflow_call:
    inputs:
      verbose:
        required: false
        type: string
      image:
        required: true
        type: string
      imagePullPolicy:
        required: true
        type: string
      stepRunnerPackageName:
        required: true
        type: string
      venvPath:
        required: true
        type: string
      stepName:
        required: true
        type: string
      stepRunnerConfigDir:
        required: true
        type: string

jobs:
  continous-integration:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: ci-generate-metadata
        uses: ploigos/ploigos-github-action@psr-action
        with:
          - stepName: "generate-metadata"
      - name: ci-create-container-image
        uses: ploigos/ploigos-github-action@psr-action
        with:
          - stepName: "create-container-image"