# This Github workflow will run the Report step of the Ploigos workflow.
name: Minimal Workflow

on:
  workflow_call:
    inputs:
      ArgoCDSecret:
        required: true
        default: ${{ secrets.ARGOCDSECRET }}
        type: string
      verbose:
        required: false
        default: true
        type: string
      stepRunnerConfigDir:
        required: false
        default: .
        type: string
jobs:
  continuous-integration:
    runs-on: [self-hosted, python]
    steps:

      - name: setup-app-clone
        uses: actions/checkout@v3

      - name: setup-workflow-step-runner
        run: pip install --upgrade git+https://github.com/ploigos/ploigos-step-runner.git@main

      - name: ci-generate-metadata
        run: psr -s generate-metadata -c ${{ inputs.stepRunnerConfigDir }}/psr.yaml

      - name: ci-package-application
        run: psr -s package -c ${{ inputs.stepRunnerConfigDir }}/psr.yaml

      - name: ci-create-container-image
        run: psr -s create-container-image -c ${{ inputs.stepRunnerConfigDir }}/psr.yaml /ploigos/generated-psr

      - name: ci-push-container-image-to-repository
        run: psr -s push-container-image -c ${{ inputs.stepRunnerConfigDir }}/psr.yaml /ploigos/generated-psr --step-config container-image-push-repository=aagreen/java-github-example

      - name: deploy-or-update-environment-test
        run: psr -s deploy -c ${{ inputs.stepRunnerConfigDir }}/psr.yaml /ploigos/generated-psr --environment TEST --step-config argocd-password=${{ inputs.ArgoCDSecret }}
