# This Github workflow will run the Report step of the Ploigos workflow.
name: Minimal Workflow

on:
  workflow_call:
    inputs:
      verbose:
        required: false
        type: string
      image:
        required: true
        type: string
      imagePullPolicy:
        required: true
        type: string
      stepRunnerPackageName:
        required: true
        type: string
      venvPath:
        required: true
        type: string
      stepName:
        required: true
        type: string
      stepRunnerConfigDir:
        required: true
        type: string
jobs:
  setup:
    runs-on: ubuntu-latest
    container:
      image: quay.io/ploigos/ploigos-base:latest.ubi8
    steps:
      - uses: actions/checkout@v3
      - name: setup-app-clone
        uses: ploigos/ploigos-github-workflows/.github/actions/setup-app-clone@main
      - name: setup-workflow-step-runner
        uses: ploigos/ploigos-github-workflows/.github/actions/setup-workflow-step-runner@main
      - name: setup-pgp-keys
        uses: ploigos/ploigos-github-workflows/.github/actions/setup-pgp-keys@main
  continous-integration:
    needs: setup
    runs-on: ubuntu-latest
    container:
      image: quay.io/ploigos/ploigos-base:latest.ubi8
    steps:
      - uses: actions/checkout@v3
      - name: ci-generate-metadata
        uses: ploigos/ploigos-github-workflows/.github/actions/ci-generate-metadata@main
      - name: ci-package-application
        uses: ploigos/ploigos-github-workflows/.github/actions/ci-package-application@main
      - name: ci-create-container-image
        uses: ploigos/ploigos-github-workflows/.github/actions/ci-create-container-image@main
      - name: ci-push-container-image-to-repository
        uses: ploigos/ploigos-github-workflows/.github/actions/ci-push-container-image-to-repository@main
  dev:
    needs: continous-integration
    runs-on: ubuntu-latest
    container:
      image: quay.io/ploigos/ploigos-base:latest.ubi8
    steps:
      - uses: actions/checkout@v3
      - name: deploy-or-update-environment
        uses: ploigos/ploigos-github-workflows/.github/actions/deploy-or-update-environment@main
  test:
    needs: dev
    runs-on: ubuntu-latest
    container:
      image: quay.io/ploigos/ploigos-base:latest.ubi8
    steps:
      - uses: actions/checkout@v3
      - name: deploy-or-update-environment
        uses: ploigos/ploigos-github-workflows/.github/actions/deploy-or-update-environment@main
  report:
    needs: test
    runs-on: ubuntu-latest
    container:
      image: quay.io/ploigos/ploigos-base:latest.ubi8
    steps:
      - uses: actions/checkout@v3
      - name: report
        uses: ploigos/ploigos-github-workflows/.github/actions/report@main