# This Github workflow will run the Report step of the Ploigos workflow.
name: Report

on:
  workflow_call:
    inputs:
      verbose:
        required: false
        type: string
      image:
        required: true
        type: string
      imagePullPolicy:
        required: true
        type: string
      stepRunnerPackageName:
        required: true
        type: string
      venvPath:
        required: true
        type: string
      stepName:
        required: true
        type: string
      stepRunnerConfigDir:
        required: true
        type: string
      environment:
        required: true
        type: string

jobs:
  report:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: report
        run: |
          echo 'Report'
