name: Setup PGP Keys

on:
  workflow_call:
    inputs:
      verbose:
        required: false
        type: string
      image:
        required: true
        type: string
      imagePullPolicy:
        required: true
        type: string
      pgpKeysSecretName:
        required: true
        type: string

jobs:
  setup-app-clone:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: setup-pgp-keys
        run: |
          echo 'Setup PGP Keys'
