name: Setup App Clone

on:
  workflow_call:
    inputs:
      verbose:
        required: false
        type: string
      image:
        required: true
        type: string
      imagePullPolicy:
        required: true
        type: string
      url:
        required: true
        type: string
      revision:
        required: true
        type: string
      deleteExisting:
        required: true
        type: string
      sslVerify:
        required: true
        type: string
      refspec:
        required: true
        type: string

jobs:
  setup-app-clone:
    runs-on: ubuntu-latest
    container:
      image: quay.io/ploigos/ploigos-base:latest.ubi8
    steps:
      - name: setup-app-clone
        run: |
          psr --help