name: Setup Workflow Step Runner

on:
  workflow_call:
    inputs:
      verbose:
        required: false
        type: string
      image:
        required: true
        type: string
      imagePullPolicy:
        required: true
        type: string
      stepRunnerPackageName:
        required: true
        type: string
      stepRunnerUpdateLibrary:
        required: true
        type: string
      stepRunnerLibSourceUrl:
        required: true
        type: string
      stepRunnerLibIndexUrl:
        required: true
        type: string
      stepRunnerLibExtraIndexUrl:
        required: true
        type: string
      stepRunnerLibVersion:
        required: true
        type: string

jobs:
  setup-workflow-step-runner:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: setup workflow step runner
        run: |
          echo 'Setup Workflow Step Runner'
