# This Github workflow will run the Test Deploy or Update Environment step of the Ploigos workflow.
name: Test Deploy or Update Environment

on:
  workflow_call:
    inputs:
      verbose:
        required: false
        type: string
      image:
        required: true
        type: string
      imagePullPolicy:
        required: true
        type: string
      stepRunnerPackageName:
        required: true
        type: string
      venvPath:
        required: true
        type: string
      stepName:
        required: true
        type: string
      stepRunnerConfigDir:
        required: true
        type: string
      environment:
        required: true
        type: string

jobs:
  test-deploy-or-update-environment:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: test-deploy-or-update-environment
        run: |
          echo 'Test Deploy or Update Environment'
